-- Install configuration: ""
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/launch
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/launch/rviz_launch.py
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/launch/sensors_launch.py
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/launch/slam_toolbox_launch.py
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/config
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/config/rplidar_node.yaml
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/config/mapper_params_online_async.yaml
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/rviz
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/rviz/create3_lidar_slam.rviz
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/ament_index/resource_index/package_run_dependencies/create3_lidar_slam
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/ament_index/resource_index/parent_prefix_path/create3_lidar_slam
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/environment/ament_prefix_path.sh
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/environment/ament_prefix_path.dsv
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/environment/path.sh
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/environment/path.dsv
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/local_setup.bash
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/local_setup.sh
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/local_setup.zsh
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/local_setup.dsv
-- Installing: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/package.dsv
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/ament_index/resource_index/packages/create3_lidar_slam
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/cmake/create3_lidar_slamConfig.cmake
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/cmake/create3_lidar_slamConfig-version.cmake
-- Up-to-date: /home/locobot/locobot_ws/install/create3_lidar_slam/share/create3_lidar_slam/package.xml
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 65, in build
    has_install_target = await has_target(args.build_base, 'install')
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 57, in has_target
    return target in await get_makefile_targets(path)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 77, in get_makefile_targets
    output = await check_output([
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/cmake', '--build', '/home/locobot/locobot_ws/build/create3_lidar_slam', '--target', 'help'] to pass: 
